spring:
  application:
    name: dbservice

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8032/eureka/
  instance:
    hostname: localhost